In [5]:
import numpy as np

## np.array() - 1D

In [1]:
my_list = [567396, 567889, 567445, 568034]
my_list

[567396, 567889, 567445, 568034]

In [2]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr

array([567396, 567889, 567445, 568034])

In [ ]:
my_list = [19,'female',27.9,0,True,'southwest',16884.924]
my_list

[19, 'female', 27.9, 0, True, 'southwest', 16884.924]

In [ ]:
print(f"* The index 0 is:  {my_list[0]}, and its data type is {type(my_list[0])}")
print(f"* The index 1 is:  {my_list[1]}, and its data type is {type(my_list[1])}")

* The index 0 is:  19, and its data type is <class 'int'>
* The index 1 is:  female, and its data type is <class 'str'>


In [ ]:
arr.dtype

dtype('O')

In [ ]:
arr = np.array(my_list,dtype=object)
arr

array([19, 'female', 27.9, 0, True, 'southwest', 16884.924], dtype=object)

In [ ]:
# now dtype give O as Object output
arr.dtype

dtype('O')

In [ ]:
my_list = [8, 8.5]
my_list

[8, 8.5]

In [ ]:
arr = np.array(my_list, dtype=object)
arr

array([8, 8.5], dtype=object)

In [ ]:
print(arr.dtype)

object


In [ ]:
arr.dtype

dtype('O')

## np.array()-2D

In [ ]:
my_list = [ [536365,  17850,  6], [536366,  17850,  6], [536367, 13047, 32] ]
my_list

[[536365, 17850, 6], [536366, 17850, 6], [536367, 13047, 32]]

In [ ]:
arr = np.array(my_list)
arr

array([[536365,  17850,      6],
       [536366,  17850,      6],
       [536367,  13047,     32]])

In [ ]:
my_2dlist = [['A','B'],['C','D']]
arr = np.array(my_2dlist)
arr

array([['A', 'B'],
       ['C', 'D']], dtype='<U1')

## np.arange()

In [ ]:
arr = np.arange(start=1, stop=10, step=1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(start=1, stop=10, step=.5)
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

## np.zeros() - 2D and 3D

In [ ]:
arr = np.zeros(shape=(2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.zeros(shape=(2,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## np.ones()

In [ ]:
# 1-D

arry = np.ones(shape=3)
arry

array([1., 1., 1.])

In [ ]:
# 2-D

arry = np.ones(shape=(2,5))
arry

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.linspace(start=1,stop=1,num=1)

In [ ]:
arr = np.linspace(start=1,stop=5,num=3)
arr

array([1., 3., 5.])

In [ ]:
arr = np.linspace(start=10,stop=50,num=10)
arr

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [ ]:
arr = np.linspace(start=-3,stop=5,num=9)
arr

array([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

## np.random.rand()

In [ ]:
# 2-D array

arr = np.random.rand(2,2)
arr

array([[0.75542376, 0.91190398],
       [0.42912552, 0.3984285 ]])

In [ ]:
# 3-D array

arr = np.random.rand(2,2,3)
arr

array([[[0.74358142, 0.25692186, 0.55351127],
        [0.48130684, 0.01651571, 0.29623486]],

       [[0.6613945 , 0.47040983, 0.76355758],
        [0.49799413, 0.50123969, 0.01913725]]])

In [ ]:
# 2-D array

arr = np.random.rand(8,2)
arr

array([[0.87898671, 0.58539125],
       [0.66197951, 0.98229199],
       [0.0019391 , 0.97754318],
       [0.54315783, 0.03695227],
       [0.99861477, 0.71233926],
       [0.11602105, 0.76420349],
       [0.80887766, 0.6100533 ],
       [0.80077598, 0.81609283]])

In [ ]:
# 1-D array

arr = np.random.rand(25)
arr

array([0.55619482, 0.20325383, 0.17871603, 0.42838724, 0.3332283 ,
       0.84046903, 0.6832278 , 0.54251019, 0.77046564, 0.38866789,
       0.90930097, 0.3249484 , 0.70593521, 0.35167023, 0.30191626,
       0.36066769, 0.11260217, 0.06597185, 0.35197916, 0.43741452,
       0.84711373, 0.625838  , 0.67715056, 0.37137288, 0.42683082])

## np.random.randint(low = 1, high = 10, size = 5)

In [ ]:
# 1-d array, shape: 5 elements

arr = np.random.randint(low=10,high=50,size=5)
arr

array([14, 19, 49, 32, 41])

# 2-d array, shape: 4 rows x 3 columns

arr = np.random.randint(low=250,high=888,size=(4,3))
arr 

In [ ]:
# 3-d array, shape: 4 sets x 3rows(in each set) x 2 columns

arr = np.random.randint(low=250,high=888,size=(4,3,2))
arr 

array([[[284, 836],
        [468, 543],
        [651, 456]],

       [[427, 881],
        [276, 702],
        [769, 571]],

       [[278, 856],
        [471, 302],
        [402, 727]],

       [[368, 342],
        [694, 769],
        [420, 680]]])

## np.random.seed(seed = 1)

In [ ]:
np.random.seed(seed=1)
arr = np.random.randint(low=10,high=50,size=3) # Size is the number of samples
arr

array([47, 22, 18])

In [ ]:
np.random.seed(seed=4)
arr = np.random.randint(low=10,high=50,size=5)
arr

array([15, 11, 33, 18, 19])

In [ ]:
np.random.seed(seed=1)
arr = np.random.randint(low=1,high=150,size=30)
arr

array([ 38, 141,  73, 138, 134,  80, 145, 130,  72, 135,  26,  21, 102,
       147, 140, 143,  51,  69,  97,  87, 142, 138,   8,  64,  62,  23,
        58,   2, 129,  61])