In [2]:
import numpy as np

In [3]:
np.random.seed(seed=0)
arr = np.random.randint(low=1,high=150,size=30) # size is the number of samples in the output.
arr

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89, 141,  59,  40,
        88,  89,  82,  26,  78,  73,  10, 149, 116,  80,  83, 100,  30,
       148, 148, 143,  33])

In [6]:
arr_reshaped = arr.reshape(5,6)  # 2-d array, 3 x 10
arr_reshaped

array([[ 48, 118,  68, 104,  10,  22],
       [ 37,  88,  71,  89, 141,  59],
       [ 40,  88,  89,  82,  26,  78],
       [ 73,  10, 149, 116,  80,  83],
       [100,  30, 148, 148, 143,  33]])

In [7]:
arr_reshaped = arr.reshape(3,15)  # 2-d array, 3 x 15. Need to change seed
arr_reshaped

ValueError: cannot reshape array of size 30 into shape (3,15)

In [109]:
arr_reshaped = arr.reshape(3,5,2)  # 3-d array, 3x5x2
arr_reshaped

array([[[ 48, 118],
        [ 68, 104],
        [ 10,  22],
        [ 37,  88],
        [ 71,  89]],

       [[141,  59],
        [ 40,  88],
        [ 89,  82],
        [ 26,  78],
        [ 73,  10]],

       [[149, 116],
        [ 80,  83],
        [100,  30],
        [148, 148],
        [143,  33]]])

In [111]:
arr = np.arange(start=1,stop=9,step=1)
print(f"array: \n {arr} \n\n"
      f"array shape: {arr.shape}")

array: 
 [1 2 3 4 5 6 7 8] 

array shape: (8,)


In [113]:
arr_reshape = arr.reshape(-1,1)  

# it is a 2-D array because you passed a tuple with 2 items
# the -1 means 'unknown', so you don't know how many rows this 2-D array will have
# the 1 means you want a single column

print(f"array: \n {arr_reshape} \n\n"
      f"array shape: {arr_reshape.shape}")

array: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 

array shape: (8, 1)


In [115]:
arr_reshape = arr.reshape(-1,2)
print(f'array: \n {arr_reshape}'
        f'array shape: {arr_reshape.shape}')

array: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]array shape: (4, 2)


## .flatten(), this transform multidimensional array to 1-D array

In [117]:
np.random.seed(seed=0)
arr = np.random.randint(low=1,high=150,size=(2,5))
arr

array([[ 48, 118,  68, 104,  10],
       [ 22,  37,  88,  71,  89]])

In [120]:
arr_flatten = arr.flatten()
arr_flatten

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89])

In [126]:
# .reshape(-1) can also work as .flatten()

arr_reshape = arr.reshape(-1)
arr_reshape

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89])

In [128]:
arr

array([[ 48, 118,  68, 104,  10],
       [ 22,  37,  88,  71,  89]])

In [130]:
arr.min()

10

In [132]:
arr.max()

118

In [134]:
arr.mean()

65.5

In [142]:
# .argmin() gives min value Index position

arr.argmin()

4

In [144]:
# .argmax() gives max value Index position

arr.argmax()

1

In [156]:
# If you want the index position for the minimum value, per column, you just add axis=0 to .argmin()
arr.argmin(axis=0)

array([1, 1, 0, 1, 0])

In [154]:
# If you want the index position for the minimum value, per row, you just add axis=1 to .argmin().

arr.argmin(axis=1)

array([4, 0])

In [158]:
arr = np.arange(start=1,stop=11,step=1).reshape(5,2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [160]:
print(
    f"* Array:\n {arr} \n\n"
    f"* Array shape: \n {arr.shape} \n\n"
    f"* Array type: \n {arr.dtype}"
    )

* Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

* Array shape: 
 (5, 2) 

* Array type: 
 int64


In [6]:
np.random.seed(seed=0)
arr = np.random.randn(2,4)
arr

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721]])

In [164]:
arr.dtype

dtype('float64')

In [166]:
print(
    f"* Array:\n {arr} \n\n"
    f"* Array shape: \n {arr.shape} \n\n"
    f"* Array type: \n {arr.dtype}"
    )

* Array:
 [[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]] 

* Array shape: 
 (2, 4) 

* Array type: 
 float64
