In [1]:
import numpy as np

In [17]:
np.random.seed(seed=1)
np.random.randint(low=10,high=50,size=8)

array([47, 22, 18, 19, 21, 15, 25, 10])

In [21]:
np.random.seed(seed=1)
np.random.randint(low=10,high=50,size=(3,3))

array([[47, 22, 18],
       [19, 21, 15],
       [25, 10, 26]])

In [39]:
np.arange(start=0,stop=36).reshape(3,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [46]:
np.random.seed(seed=1)
np.random.randint(low=1,high=30,size=36).reshape(4,3,3)

array([[[ 6, 12, 13],
        [ 9, 10, 12],
        [ 6, 16,  1]],

       [[17,  2, 13],
        [ 8, 14, 29],
        [ 7, 26, 19]],

       [[21,  6, 19],
        [21, 12, 29],
        [11, 29, 15]],

       [[19,  5, 24],
        [24, 10, 18],
        [24,  1, 23]]])

In [50]:
# 4-D array

np.random.seed(seed=1)
np.random.randint(low=10,high=50,size=(2,3,4,5))

array([[[[47, 22, 18, 19, 21],
         [15, 25, 10, 26, 11],
         [22, 17, 16, 35, 30],
         [47, 28, 30, 21, 38]],

        [[39, 24, 14, 33, 33],
         [40, 42, 32, 23, 19],
         [17, 32, 11, 10, 27],
         [18, 34, 23, 18, 40]],

        [[17, 13, 16, 31, 13],
         [14, 34, 22, 36, 26],
         [28, 25, 10, 14, 35],
         [44, 33, 17, 36, 35]]],


       [[[32, 19, 13, 49, 33],
         [46, 37, 47, 29, 48],
         [18, 42, 44, 20, 33],
         [25, 33, 35, 17, 38]],

        [[20, 42, 34, 33, 11],
         [23, 13, 10, 23, 16],
         [31, 16, 12, 22, 37],
         [31, 21, 17, 23, 18]],

        [[21, 22, 30, 40, 46],
         [49, 17, 14, 28, 42],
         [23, 20, 33, 27, 17],
         [34, 20, 38, 30, 42]]]])

In [52]:
np.random.seed(seed=1)
np.random.randint(low=10,high=50,size=(2,2,3,4,5))

array([[[[[47, 22, 18, 19, 21],
          [15, 25, 10, 26, 11],
          [22, 17, 16, 35, 30],
          [47, 28, 30, 21, 38]],

         [[39, 24, 14, 33, 33],
          [40, 42, 32, 23, 19],
          [17, 32, 11, 10, 27],
          [18, 34, 23, 18, 40]],

         [[17, 13, 16, 31, 13],
          [14, 34, 22, 36, 26],
          [28, 25, 10, 14, 35],
          [44, 33, 17, 36, 35]]],


        [[[32, 19, 13, 49, 33],
          [46, 37, 47, 29, 48],
          [18, 42, 44, 20, 33],
          [25, 33, 35, 17, 38]],

         [[20, 42, 34, 33, 11],
          [23, 13, 10, 23, 16],
          [31, 16, 12, 22, 37],
          [31, 21, 17, 23, 18]],

         [[21, 22, 30, 40, 46],
          [49, 17, 14, 28, 42],
          [23, 20, 33, 27, 17],
          [34, 20, 38, 30, 42]]]],



       [[[[22, 11, 40, 34, 28],
          [43, 12, 38, 49, 44],
          [20, 42, 28, 32, 16],
          [12, 17, 49, 25, 15]],

         [[27, 30, 32, 47, 23],
          [43, 30, 20, 42, 35],
          [31, 49, 4