In [3]:
import numpy as np

## 1D arrays

In [6]:
arr = np.arange(start=0,stop=26,step=2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [8]:
arr[8]

16

In [10]:
arr[0]

0

In [12]:
arr[1:5]

array([2, 4, 6, 8])

In [14]:
arr[0:5]

array([0, 2, 4, 6, 8])

In [16]:
arr[:5]

array([0, 2, 4, 6, 8])

In [18]:
arr[7:]

array([14, 16, 18, 20, 22, 24])

## 2D arrays

In [14]:
np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=(3,5))
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

### Indexing full row

In [16]:
#  The row is at index 1, and the column is at index 0

arr[1, ] # it is not "arr[1:0]"

array([21, 19, 23, 14, 38])

In [22]:
# 1 is row index, ',:1' is 0 to 1 column index (1 is exclusive)

arr[1,:1]

array([21, 19])

In [11]:
arr[1,1:]

array([19, 23, 14, 38])

In [11]:
arr[:,3]

array([16, 14, 39])

In [15]:
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

In [17]:
arr[:2,1:]

array([[21, 27, 16, 33],
       [19, 23, 14, 38]])

### Slice ranges

In [22]:
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

In [24]:
arr[:2,1:]

array([[21, 27, 16, 33],
       [19, 23, 14, 38]])

In [26]:
arr[1:4,3:]

array([[14, 38],
       [39, 29]])

## 3D arrays

In [28]:
np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=(3,3,4))  # 3-d array: in this case, 3 arrays of 3x4
arr

array([[[41, 21, 27, 16],
        [33, 21, 19, 23],
        [14, 38, 10, 15]],

       [[22, 39, 29, 18],
        [39, 44, 18, 29],
        [20, 22, 41, 33]],

       [[10, 19, 18, 46],
        [29, 45, 38, 17],
        [20, 49, 48, 19]]])

In [34]:
# Retrieving a single element
# Index 1 (second array), the row is at index 0, and the column is at index 0
arr[1,0,0]

22

In [38]:
# Retrieve a row
# Index 2 (last array), the row is at index 1, and all columns

arr[2,1,:]

array([29, 45, 38, 17])

In [46]:
arr[0,0:,2]

array([27, 19, 10])

In [48]:
# The concept is very similar to a 2-D array
# Pick the array at index 0 (first array), rows from index 0 to index 2 (exclusive) and columns from index 0 to index 3 (exclusive)
# The output is a 2-D array since you are grabbing a range

arr[0,:2,:3]

array([[41, 21, 27],
       [33, 21, 19]])

In [50]:
arr[0:2,:2,:3]

array([[[41, 21, 27],
        [33, 21, 19]],

       [[22, 39, 29],
        [39, 44, 18]]])

In [52]:
arr[1:,0:,1:3]

array([[[39, 29],
        [44, 18],
        [22, 41]],

       [[19, 18],
        [45, 38],
        [49, 48]]])

In [33]:
arr.shape

(3, 3, 4)