In [1]:
import numpy as np

In [5]:
# 1D array

np.random.seed(seed=101)
arr = np.random.randint(low=10, high=50, size=9)
arr

array([41, 21, 27, 16, 33, 21, 19, 23, 14])

In [13]:
arr[-3:]

array([19, 23, 14])

In [15]:
arr[-3:-1]

array([19, 23])

In [23]:
# 2D array

np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=(3,5))
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

In [43]:
# Rows: You will get all rows due to the first ":"
# Columns: "-2:" means: count 2 index positions (inclusive) from the end. 
# You will start moving to the right and continue until the end since there is no number after ":"

arr[:,-2:]

array([[16, 33],
       [14, 38],
       [39, 29]])

In [39]:
arr[-2:,-3:-2]

array([], shape=(0, 3), dtype=int64)

In [45]:
# 3D array

np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=(3,5,4))
arr

array([[[41, 21, 27, 16],
        [33, 21, 19, 23],
        [14, 38, 10, 15],
        [22, 39, 29, 18],
        [39, 44, 18, 29]],

       [[20, 22, 41, 33],
        [10, 19, 18, 46],
        [29, 45, 38, 17],
        [20, 49, 48, 19],
        [28, 17, 49, 25]],

       [[10, 22, 27, 21],
        [25, 43, 39, 34],
        [46, 29, 45, 40],
        [20, 49, 30, 37],
        [18, 32, 36, 33]]])

In [103]:
arr[-2, -3:-1, -3:]

array([[45, 38, 17],
       [49, 48, 19]])