In [1]:
import numpy as np

In [3]:
np.random.seed(seed=10)
arr = np.random.randint(low = 1,high = 25, size = (3,5))
arr

array([[10,  5, 16,  1, 18],
       [17, 18,  9, 10,  1],
       [11,  9, 23,  5, 20]])

In [13]:
# Returns Boolean output

arr > 10

array([[False, False,  True, False,  True],
       [ True,  True, False, False, False],
       [ True, False,  True, False,  True]])

In [15]:
# Return in list format

arr[arr>10]

array([16, 18, 17, 18, 11, 23, 20])

In [19]:
arr[arr<7]

array([5, 1, 1, 5])

In [27]:
arr[(arr>7) & (arr<20)]

array([10, 16, 18, 17, 18,  9, 10, 11,  9])

In [29]:
arr[(arr<=5) | (arr>15)]

array([ 5, 16,  1, 18, 17, 18,  1, 23,  5, 20])

In [31]:
arr

array([[10,  5, 16,  1, 18],
       [17, 18,  9, 10,  1],
       [11,  9, 23,  5, 20]])

In [33]:
# Values less than 2 (including 2) or greater than 18 and also want values that are equal to 9

arr[ ((arr<=2) | (arr > 18)) | (arr == 9) ]

array([ 1,  9,  1,  9, 23, 20])

In [35]:
macro_arr=np.array([[0.9,0.1],[2.1,0.1],[2.7,0.1],[4.4,0.25],[5.5,0.625],[7.9,1.125],[8.7,2],[9.4,3.25]])
macro_arr

array([[0.9  , 0.1  ],
       [2.1  , 0.1  ],
       [2.7  , 0.1  ],
       [4.4  , 0.25 ],
       [5.5  , 0.625],
       [7.9  , 1.125],
       [8.7  , 2.   ],
       [9.4  , 3.25 ]])

In [41]:
macro_arr [ ((macro_arr==.1) | (macro_arr<=.9)) | (macro_arr>9)]

array([0.9  , 0.1  , 0.1  , 0.1  , 0.25 , 0.625, 9.4  ])