In [1]:
import numpy as np

In [5]:
# Python list comprehension to multiply each element by 3

[3*x for x in [2, 3, 4]]

[6, 9, 12]

In [7]:
list = []
for x in [2,3,4]:
    list.append(3*x)
print(list)

[6, 9, 12]


In [9]:
# Create a NumPy array from the same Python list and assign it to variable a
a = np.array([2,3,4])
# Multiply the variable by 3
a * 3

array([ 6,  9, 12])

In [11]:
np.random.seed(seed=2)
arr1 = np.random.randint(low=0,high=8,size=(3,5))
arr1

array([[0, 7, 5, 0, 6],
       [3, 2, 3, 0, 7],
       [2, 1, 7, 3, 5]])

In [13]:
np.random.seed(seed=1)
arr2 = np.random.randint(low=0,high=50,size=(3,5))
arr2

array([[37, 43, 12,  8,  9],
       [11,  5, 15,  0, 16],
       [ 1, 12,  7, 45,  6]])

In [19]:
# You can sum a constant to a numeric array

arr2 + 2

array([[39, 45, 14, 10, 11],
       [13,  7, 17,  2, 18],
       [ 3, 14,  9, 47,  8]])

In [97]:
# You can divide the array by a constant

arr1 / 7

array([[0.        , 1.        , 0.71428571, 0.        , 0.85714286],
       [0.42857143, 0.28571429, 0.42857143, 0.        , 1.        ],
       [0.28571429, 0.14285714, 1.        , 0.42857143, 0.71428571]])

In [31]:
arr1 * 1.41

array([[0.  , 9.87, 7.05, 0.  , 8.46],
       [4.23, 2.82, 4.23, 0.  , 9.87],
       [2.82, 1.41, 9.87, 4.23, 7.05]])

In [33]:
arr1 - 1.41

array([[-1.41,  5.59,  3.59, -1.41,  4.59],
       [ 1.59,  0.59,  1.59, -1.41,  5.59],
       [ 0.59, -0.41,  5.59,  1.59,  3.59]])

In [35]:
arr1 ** 3

array([[  0, 343, 125,   0, 216],
       [ 27,   8,  27,   0, 343],
       [  8,   1, 343,  27, 125]])

In [37]:
arr1 + arr2

array([[37, 50, 17,  8, 15],
       [14,  7, 18,  0, 23],
       [ 3, 13, 14, 48, 11]])

In [39]:
arr1 * arr2

array([[  0, 301,  60,   0,  54],
       [ 33,  10,  45,   0, 112],
       [  2,  12,  49, 135,  30]])

In [41]:
arr2 - arr1

array([[37, 36,  7,  8,  3],
       [ 8,  3, 12,  0,  9],
       [-1, 11,  0, 42,  1]])

In [43]:
# In this case, when the numerator and denominator elements are zero, the operation's result for that element is nan (not a number).

arr1/arr2

/var/folders/2h/2zcs8h612kxcwf4_nb9dj5dm0000gn/T/ipykernel_28912/3936148295.py:3: RuntimeWarning: invalid value encountered in divide
  arr1/arr2


array([[0.        , 0.1627907 , 0.41666667, 0.        , 0.66666667],
       [0.27272727, 0.4       , 0.2       ,        nan, 0.4375    ],
       [2.        , 0.08333333, 1.        , 0.06666667, 0.83333333]])

In [47]:
# Another use case is when the denominator element is zero, the operation's result for that element is inf (infinite).

1/arr2

/var/folders/2h/2zcs8h612kxcwf4_nb9dj5dm0000gn/T/ipykernel_28912/1278033217.py:3: RuntimeWarning: divide by zero encountered in divide
  1/arr2


array([[0.02702703, 0.02325581, 0.08333333, 0.125     , 0.11111111],
       [0.09090909, 0.2       , 0.06666667,        inf, 0.0625    ],
       [1.        , 0.08333333, 0.14285714, 0.02222222, 0.16666667]])

In [83]:
np.random.seed(seed=101)
arr = np.random.randint(low=-10,high=25,size=(3,5))
arr

array([[ 21,   1,   7,  -4,  13],
       [  1,  -1,   3,  -6,  18],
       [-10,  -5,   2,  19,   9]])

In [53]:
# When the element is negative, the square root is nan (not a number), considering the "land of the real numbers".

np.sqrt(arr)

/var/folders/2h/2zcs8h612kxcwf4_nb9dj5dm0000gn/T/ipykernel_28912/1604984372.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[4.58257569, 1.        , 2.64575131,        nan, 3.60555128],
       [1.        ,        nan, 1.73205081,        nan, 4.24264069],
       [       nan,        nan, 1.41421356, 4.35889894, 3.        ]])

In [57]:
# The absolute value of each element with np.abs()

np.abs(arr)

array([[21,  1,  7,  4, 13],
       [ 1,  1,  3,  6, 18],
       [10,  5,  2, 19,  9]])

In [63]:
# calculate the exponential in base 2 (2 ** x) of all elements

np.exp2(arr)

array([[2.097152e+06, 2.000000e+00, 1.280000e+02, 6.250000e-02,
        8.192000e+03],
       [2.000000e+00, 5.000000e-01, 8.000000e+00, 1.562500e-02,
        2.621440e+05],
       [9.765625e-04, 3.125000e-02, 4.000000e+00, 5.242880e+05,
        5.120000e+02]])

In [67]:
# Natural logarithm for each element using np.log()

np.log(arr)

/var/folders/2h/2zcs8h612kxcwf4_nb9dj5dm0000gn/T/ipykernel_28912/2861197341.py:3: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([[3.04452244, 0.        , 1.94591015,        nan, 2.56494936],
       [0.        ,        nan, 1.09861229,        nan, 2.89037176],
       [       nan,        nan, 0.69314718, 2.94443898, 2.19722458]])

In [69]:
# base-2 logarithm for each element using np.log2()

np.log2(arr)

/var/folders/2h/2zcs8h612kxcwf4_nb9dj5dm0000gn/T/ipykernel_28912/1180703931.py:3: RuntimeWarning: invalid value encountered in log2
  np.log2(arr)


array([[4.39231742, 0.        , 2.80735492,        nan, 3.70043972],
       [0.        ,        nan, 1.5849625 ,        nan, 4.169925  ],
       [       nan,        nan, 1.        , 4.24792751, 3.169925  ]])

In [71]:
#  base-10 logarithm for each element using np.log10()

np.log10(arr)

/var/folders/2h/2zcs8h612kxcwf4_nb9dj5dm0000gn/T/ipykernel_28912/1496859976.py:3: RuntimeWarning: invalid value encountered in log10
  np.log10(arr)


array([[1.32221929, 0.        , 0.84509804,        nan, 1.11394335],
       [0.        ,        nan, 0.47712125,        nan, 1.25527251],
       [       nan,        nan, 0.30103   , 1.2787536 , 0.95424251]])

In [75]:
# Standard Deviation

np.std(arr)

9.344279295673667

In [81]:
arr

array([[ 21,   1,   7,  -4,  13],
       [  1,  -1,   3,  -6,  18],
       [-10,  -5,   2,  19,   9]])

In [77]:
# Max value of the array

np.max(arr)

21

In [85]:
np.argmin(arr)

10

In [87]:
arr

array([[ 21,   1,   7,  -4,  13],
       [  1,  -1,   3,  -6,  18],
       [-10,  -5,   2,  19,   9]])

In [89]:
#Think of the axis parameter as telling NumPy which direction you want to sum along:

# axis=0: Sum vertically (down the columns). This collapses the first dimension (stacks of arrays).
# axis=1: Sum horizontally (across rows). This collapses the second dimension (rows).
# axis=2: Sum along the last axis (across columns), collapsing the third dimension.

np.sum(arr, axis=0)

array([12, -5, 12,  9, 40])

In [93]:
macro_arr=np.array([[513850, 0.4, 0.5],[516876, 0.3, 0.5],[518915, 0.4, 0.5],[521920, 0.4, 0.5],[523813, 0.7, 0.5],[526750, 0.7, 0.5],[528712, 1.0, 0.25],[532082, 1.5, 0.25]])
macro_arr

array([[5.13850e+05, 4.00000e-01, 5.00000e-01],
       [5.16876e+05, 3.00000e-01, 5.00000e-01],
       [5.18915e+05, 4.00000e-01, 5.00000e-01],
       [5.21920e+05, 4.00000e-01, 5.00000e-01],
       [5.23813e+05, 7.00000e-01, 5.00000e-01],
       [5.26750e+05, 7.00000e-01, 5.00000e-01],
       [5.28712e+05, 1.00000e+00, 2.50000e-01],
       [5.32082e+05, 1.50000e+00, 2.50000e-01]])

In [99]:
macro_arr[:,0]

array([513850., 516876., 518915., 521920., 523813., 526750., 528712.,
       532082.])

In [103]:
np.sum(macro_arr[:4,0])

2071561.0

In [105]:
macro_arr[:,2] - macro_arr[:,1]

array([ 0.1 ,  0.2 ,  0.1 ,  0.1 , -0.2 , -0.2 , -0.75, -1.25])

In [107]:
np.mean((macro_arr[:,1:]),axis=0)

array([0.675 , 0.4375])

In [109]:
np.std((macro_arr[:,1:]),axis=0)

array([0.3799671 , 0.10825318])